[package]
name = "xxhash32"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "xxhash32"
path = "src/bin.rs"

[dependencies]
byteorder = "1.5.0"